### ISSUE TITLE
Update StateQuality

### ISSUE THREAD

**Issue by jpawlowski** [AlCalzone/virtual-tsc#16]
The values for StateQuality in `test/ioBroker.d.ts` seem outdated, for example, one could receive the following TypeScript error:

`Type '64' is not assignable to type 'StateQuality | undefined'.`

I think the values in

https://github.com/AlCalzone/virtual-tsc/blob/90cae6d2da39e4aae8c3e22c9ccefd526aabf16c/test/ioBroker.d.ts#L11-L21

shall be updated with values from

https://github.com/ioBroker/ioBroker.docs/blob/6cf3906bc43bd3b31821902c78abd8babe4f93d3/docs/en/dev/objectsschema.md?plain=1#L133-L153

As an example, I had to ignore the TS errors like this https://github.com/jpawlowski/ioBroker.residents/commit/71d2e5db07039c1eb2d5f2031caee885eb64b9a4

**Comment by AlCalzone** [comment]
You're looking for the [js-controller repo](https://github.com/ioBroker/ioBroker.js-controller). This file you referenced is just a test for the compiler.

**Comment by jpawlowski** [comment]
Okay.

Do you know where to find the `StateQuality` TypeScript object definitions in [js-controller repo](https://github.com/ioBroker/ioBroker.js-controller)? I can't find them anywhere, and Google has only one match leading to this/your repository only.
