### ISSUE TITLE
Can this work in browser memory for live editing TS code and render it

### ISSUE THREAD

**Issue by gargroh** [AlCalzone/virtual-tsc#7]
Can this work in browser memory for live editing TS code and render it ?

**Comment by AlCalzone** [comment]
I haven't tried, but probably yes. You'll need to bundle all the dependencies and provide the TypeScript lib files somehow. You might want to take a look at the [monaco editor](https://github.com/Microsoft/monaco-editor) and the TypeScript playground: https://www.typescriptlang.org/play/ - they already do what you are trying to.

**Comment by gargroh** [comment]
Yeah saw that. Anyways thanks for reply and help
